name: coaching_institude
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0-188.0.dev

dependencies:
  flutter:
    sdk: flutter
  
    
  
  flutter_svg: ^2.0.9
  syncfusion_flutter_pdfviewer: ^29.1.38
  url_launcher: ^6.3.1
  random_string: ^2.3.1
  http: ^1.3.0
  youtube_player_iframe: ^5.2.1
  youtube_player_flutter: ^9.1.1
  auto_size_text: ^3.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  provider: ^6.1.4
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  webview_flutter: ^4.11.0
  webview_flutter_android: ^4.2.2
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  shared_preferences: ^2.5.3
  flutter_lints: ^5.0.0


  flutter_staggered_animations: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - lib/syllabus/dummy.pdf
    - assets/profile.png
    - assets/verified.png
    - assets/verify.png
    - assets/troffy.jpg
    - assets/verification.jpg
    - assets/logo.jpg
 
